// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3B_PmqPoURZTQeFm0yOiW4_Nirq-v3eA',
    appId: '1:158685587835:web:48dca95c5b991d9ee635de',
    messagingSenderId: '158685587835',
    projectId: 'redrabbitproject-fb661',
    authDomain: 'redrabbitproject-fb661.firebaseapp.com',
    storageBucket: 'redrabbitproject-fb661.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAntul_Rd7us-T3aynDbtSgBoJUqTXxqcI',
    appId: '1:158685587835:android:462d584e1a9fb80ae635de',
    messagingSenderId: '158685587835',
    projectId: 'redrabbitproject-fb661',
    storageBucket: 'redrabbitproject-fb661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9q8A8tfyy6jWl4KEyCqNp29uT8LAKgdo',
    appId: '1:158685587835:ios:3de03b22dd3187c8e635de',
    messagingSenderId: '158685587835',
    projectId: 'redrabbitproject-fb661',
    storageBucket: 'redrabbitproject-fb661.appspot.com',
    iosBundleId: 'com.example.userModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9q8A8tfyy6jWl4KEyCqNp29uT8LAKgdo',
    appId: '1:158685587835:ios:a85b6ce0ed4319b1e635de',
    messagingSenderId: '158685587835',
    projectId: 'redrabbitproject-fb661',
    storageBucket: 'redrabbitproject-fb661.appspot.com',
    iosBundleId: 'com.example.userModule.RunnerTests',
  );
}
