// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaKT9RH3zKy2yn3HsHpPG3LIhfNKUN3eA',
    appId: '1:890144454001:web:d8b3c6fea8bb35cf7272d0',
    messagingSenderId: '890144454001',
    projectId: 'food-delivery-app-26294',
    authDomain: 'food-delivery-app-26294.firebaseapp.com',
    storageBucket: 'food-delivery-app-26294.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkujv1-SK2f4vPIkV-skXteO_4cWHZ4QM',
    appId: '1:890144454001:android:b1950c07dd672d877272d0',
    messagingSenderId: '890144454001',
    projectId: 'food-delivery-app-26294',
    storageBucket: 'food-delivery-app-26294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzW14ZJZafwAgRaJqQftLlJslMUZE8aHI',
    appId: '1:890144454001:ios:51bf50d957711b4c7272d0',
    messagingSenderId: '890144454001',
    projectId: 'food-delivery-app-26294',
    storageBucket: 'food-delivery-app-26294.appspot.com',
    iosBundleId: 'com.example.userModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzW14ZJZafwAgRaJqQftLlJslMUZE8aHI',
    appId: '1:890144454001:ios:edcb3c560d61cc897272d0',
    messagingSenderId: '890144454001',
    projectId: 'food-delivery-app-26294',
    storageBucket: 'food-delivery-app-26294.appspot.com',
    iosBundleId: 'com.example.userModule.RunnerTests',
  );
}
